services:
  db-users:
    image: mysql:5.7.40
    restart: always
    environment:
      - MYSQL_DATABASE=coffuel
      - MYSQL_ROOT_PASSWORD=techstart_coffuel_2023
    ports:
      - "3307:3306"
    expose:
      - 3306
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=db-users
    ports:
      - 80:80
# docker-compose -p coffuel-techstart up -d
